/**
 * The Aquarius chemistry library — the searchable catalog of mhchem snippets
 * that backs the chemistry toolbar and the chemistry palette. It deliberately
 * mirrors lib/symbols.ts (same entry shape, same picker) but is a SEPARATE
 * catalog: chemistry and math symbols are parallel systems, never mixed.
 *
 * Every `latex` MUST render in KaTeX with the mhchem extension loaded
 * (components/Katex.tsx imports it; lib/chemsymbols.test.ts enforces the rule).
 * Entries are stored in their full form (`\ce{...}` / `\pu{...}` / plain math
 * for quantities); when inserted into a chemistry field the routing unwraps
 * `\ce{...}` back to plain mhchem source (see lib/blocks/chem.ts `ceInner`).
 */

import type { SymbolEntry } from "@/lib/symbols";

export const CHEM_SYMBOLS: SymbolEntry[] = [
  // ── Reactions & arrows ──
  { name: "yields", latex: "\\ce{->}", category: "Reactions & arrows", aliases: ["reaction arrow", "to", "gives", "produces"] },
  { name: "reverse reaction", latex: "\\ce{<-}", category: "Reactions & arrows", aliases: ["left arrow", "from"] },
  { name: "equilibrium", latex: "\\ce{<=>}", category: "Reactions & arrows", aliases: ["reversible", "harpoons"] },
  { name: "equilibrium (right favored)", latex: "\\ce{<=>>}", category: "Reactions & arrows", aliases: ["shifted right"] },
  { name: "equilibrium (left favored)", latex: "\\ce{<<=>}", category: "Reactions & arrows", aliases: ["shifted left"] },
  { name: "resonance", latex: "\\ce{<->}", category: "Reactions & arrows", aliases: ["mesomerism", "double headed"] },
  { name: "both directions", latex: "\\ce{<-->}", category: "Reactions & arrows", aliases: ["opposing arrows"] },
  { name: "heated (Δ over arrow)", latex: "\\ce{->[\\Delta]}", category: "Reactions & arrows", aliases: ["heat", "delta arrow", "thermal"] },
  { name: "catalyst over arrow", latex: "\\ce{->[\\text{cat.}]}", category: "Reactions & arrows", aliases: ["catalyzed", "cat"] },
  { name: "gas evolved", latex: "\\ce{^}", category: "Reactions & arrows", aliases: ["up arrow", "escapes", "bubbles"] },
  { name: "precipitate", latex: "\\ce{v}", category: "Reactions & arrows", aliases: ["down arrow", "solid forms", "falls out"] },
  // ── States & phases ──
  { name: "solid", latex: "\\ce{(s)}", category: "States & phases", aliases: ["state solid"] },
  { name: "liquid", latex: "\\ce{(l)}", category: "States & phases", aliases: ["state liquid"] },
  { name: "gas", latex: "\\ce{(g)}", category: "States & phases", aliases: ["state gas", "gaseous"] },
  { name: "aqueous", latex: "\\ce{(aq)}", category: "States & phases", aliases: ["dissolved", "in water", "solution"] },
  { name: "water (liquid)", latex: "\\ce{H2O(l)}", category: "States & phases", aliases: ["state example"] },
  // ── Ions ──
  { name: "hydrogen ion", latex: "\\ce{H+}", category: "Ions", aliases: ["proton", "hydron", "acid"] },
  { name: "hydroxide", latex: "\\ce{OH-}", category: "Ions", aliases: ["base"] },
  { name: "hydronium", latex: "\\ce{H3O+}", category: "Ions", aliases: ["oxonium"] },
  { name: "electron", latex: "\\ce{e-}", category: "Ions", aliases: ["redox electron"] },
  { name: "ammonium", latex: "\\ce{NH4+}", category: "Ions" },
  { name: "sodium ion", latex: "\\ce{Na+}", category: "Ions" },
  { name: "potassium ion", latex: "\\ce{K+}", category: "Ions" },
  { name: "calcium ion", latex: "\\ce{Ca^2+}", category: "Ions" },
  { name: "magnesium ion", latex: "\\ce{Mg^2+}", category: "Ions" },
  { name: "barium ion", latex: "\\ce{Ba^2+}", category: "Ions" },
  { name: "iron(II) ion", latex: "\\ce{Fe^2+}", category: "Ions", aliases: ["ferrous"] },
  { name: "iron(III) ion", latex: "\\ce{Fe^3+}", category: "Ions", aliases: ["ferric"] },
  { name: "copper(II) ion", latex: "\\ce{Cu^2+}", category: "Ions", aliases: ["cupric"] },
  { name: "zinc ion", latex: "\\ce{Zn^2+}", category: "Ions" },
  { name: "silver ion", latex: "\\ce{Ag+}", category: "Ions" },
  { name: "aluminium ion", latex: "\\ce{Al^3+}", category: "Ions", aliases: ["aluminum"] },
  { name: "lead(II) ion", latex: "\\ce{Pb^2+}", category: "Ions" },
  { name: "chloride", latex: "\\ce{Cl-}", category: "Ions" },
  { name: "bromide", latex: "\\ce{Br-}", category: "Ions" },
  { name: "iodide", latex: "\\ce{I-}", category: "Ions" },
  { name: "fluoride", latex: "\\ce{F-}", category: "Ions" },
  { name: "nitrate", latex: "\\ce{NO3-}", category: "Ions" },
  { name: "nitrite", latex: "\\ce{NO2-}", category: "Ions" },
  { name: "sulfate", latex: "\\ce{SO4^2-}", category: "Ions", aliases: ["sulphate"] },
  { name: "sulfite", latex: "\\ce{SO3^2-}", category: "Ions", aliases: ["sulphite"] },
  { name: "sulfide", latex: "\\ce{S^2-}", category: "Ions", aliases: ["sulphide"] },
  { name: "oxide", latex: "\\ce{O^2-}", category: "Ions" },
  { name: "carbonate", latex: "\\ce{CO3^2-}", category: "Ions" },
  { name: "hydrogen carbonate", latex: "\\ce{HCO3-}", category: "Ions", aliases: ["bicarbonate"] },
  { name: "phosphate", latex: "\\ce{PO4^3-}", category: "Ions" },
  { name: "permanganate", latex: "\\ce{MnO4-}", category: "Ions" },
  { name: "dichromate", latex: "\\ce{Cr2O7^2-}", category: "Ions" },
  { name: "acetate", latex: "\\ce{CH3COO-}", category: "Ions", aliases: ["ethanoate"] },
  { name: "cyanide", latex: "\\ce{CN-}", category: "Ions" },
  { name: "tetraamminecopper(II)", latex: "\\ce{[Cu(NH3)4]^2+}", category: "Ions", aliases: ["complex ion example", "coordination"] },
  // ── Molecules & compounds ──
  { name: "water", latex: "\\ce{H2O}", category: "Molecules & compounds" },
  { name: "hydrogen peroxide", latex: "\\ce{H2O2}", category: "Molecules & compounds" },
  { name: "carbon dioxide", latex: "\\ce{CO2}", category: "Molecules & compounds" },
  { name: "carbon monoxide", latex: "\\ce{CO}", category: "Molecules & compounds" },
  { name: "oxygen", latex: "\\ce{O2}", category: "Molecules & compounds", aliases: ["dioxygen"] },
  { name: "ozone", latex: "\\ce{O3}", category: "Molecules & compounds" },
  { name: "nitrogen", latex: "\\ce{N2}", category: "Molecules & compounds", aliases: ["dinitrogen"] },
  { name: "hydrogen", latex: "\\ce{H2}", category: "Molecules & compounds", aliases: ["dihydrogen"] },
  { name: "chlorine", latex: "\\ce{Cl2}", category: "Molecules & compounds" },
  { name: "ammonia", latex: "\\ce{NH3}", category: "Molecules & compounds" },
  { name: "methane", latex: "\\ce{CH4}", category: "Molecules & compounds" },
  { name: "ethanol", latex: "\\ce{C2H5OH}", category: "Molecules & compounds", aliases: ["alcohol"] },
  { name: "acetic acid", latex: "\\ce{CH3COOH}", category: "Molecules & compounds", aliases: ["ethanoic acid", "vinegar"] },
  { name: "glucose", latex: "\\ce{C6H12O6}", category: "Molecules & compounds", aliases: ["sugar"] },
  { name: "hydrochloric acid", latex: "\\ce{HCl}", category: "Molecules & compounds" },
  { name: "sulfuric acid", latex: "\\ce{H2SO4}", category: "Molecules & compounds", aliases: ["sulphuric"] },
  { name: "nitric acid", latex: "\\ce{HNO3}", category: "Molecules & compounds" },
  { name: "phosphoric acid", latex: "\\ce{H3PO4}", category: "Molecules & compounds" },
  { name: "carbonic acid", latex: "\\ce{H2CO3}", category: "Molecules & compounds" },
  { name: "sodium hydroxide", latex: "\\ce{NaOH}", category: "Molecules & compounds", aliases: ["lye", "caustic soda"] },
  { name: "potassium hydroxide", latex: "\\ce{KOH}", category: "Molecules & compounds" },
  { name: "calcium hydroxide", latex: "\\ce{Ca(OH)2}", category: "Molecules & compounds", aliases: ["slaked lime"] },
  { name: "sodium chloride", latex: "\\ce{NaCl}", category: "Molecules & compounds", aliases: ["salt", "table salt"] },
  { name: "sodium bicarbonate", latex: "\\ce{NaHCO3}", category: "Molecules & compounds", aliases: ["baking soda", "sodium hydrogen carbonate"] },
  { name: "sodium carbonate", latex: "\\ce{Na2CO3}", category: "Molecules & compounds", aliases: ["soda ash"] },
  { name: "calcium carbonate", latex: "\\ce{CaCO3}", category: "Molecules & compounds", aliases: ["limestone", "chalk"] },
  { name: "calcium oxide", latex: "\\ce{CaO}", category: "Molecules & compounds", aliases: ["quicklime"] },
  { name: "copper(II) sulfate", latex: "\\ce{CuSO4}", category: "Molecules & compounds" },
  { name: "copper sulfate pentahydrate", latex: "\\ce{CuSO4 * 5H2O}", category: "Molecules & compounds", aliases: ["hydrate example", "blue vitriol"] },
  { name: "potassium permanganate", latex: "\\ce{KMnO4}", category: "Molecules & compounds" },
  { name: "silver nitrate", latex: "\\ce{AgNO3}", category: "Molecules & compounds" },
  { name: "iron(III) oxide", latex: "\\ce{Fe2O3}", category: "Molecules & compounds", aliases: ["rust"] },
  { name: "sulfur dioxide", latex: "\\ce{SO2}", category: "Molecules & compounds", aliases: ["sulphur dioxide"] },
  { name: "nitrogen dioxide", latex: "\\ce{NO2}", category: "Molecules & compounds" },
  // ── Isotopes & nuclear ──
  { name: "isotope notation", latex: "\\ce{^{14}_{6}C}", category: "Isotopes & nuclear", aliases: ["carbon-14", "nuclide", "mass number"] },
  { name: "uranium-235", latex: "\\ce{^{235}_{92}U}", category: "Isotopes & nuclear", aliases: ["fission"] },
  { name: "deuterium", latex: "\\ce{^{2}_{1}H}", category: "Isotopes & nuclear", aliases: ["heavy hydrogen"] },
  { name: "tritium", latex: "\\ce{^{3}_{1}H}", category: "Isotopes & nuclear" },
  { name: "alpha particle", latex: "\\ce{^{4}_{2}He}", category: "Isotopes & nuclear", aliases: ["helium nucleus", "alpha decay"] },
  { name: "beta particle", latex: "\\ce{^{0}_{-1}e}", category: "Isotopes & nuclear", aliases: ["beta decay", "electron emission"] },
  { name: "positron", latex: "\\ce{^{0}_{+1}e}", category: "Isotopes & nuclear", aliases: ["beta plus"] },
  { name: "neutron", latex: "\\ce{^{1}_{0}n}", category: "Isotopes & nuclear" },
  { name: "proton (nuclear)", latex: "\\ce{^{1}_{1}p}", category: "Isotopes & nuclear" },
  { name: "gamma ray", latex: "\\gamma", category: "Isotopes & nuclear", aliases: ["gamma decay", "photon"] },
  // ── Bonds ──
  { name: "single bond", latex: "\\ce{C-C}", category: "Bonds", aliases: ["sigma"] },
  { name: "double bond", latex: "\\ce{C=C}", category: "Bonds", aliases: ["alkene", "pi"] },
  { name: "triple bond", latex: "\\ce{C#C}", category: "Bonds", aliases: ["alkyne"] },
  { name: "structural fragment", latex: "\\ce{CH3-CH2-OH}", category: "Bonds", aliases: ["condensed formula", "ethanol structure"] },
  // ── Quantities ──
  { name: "enthalpy change", latex: "\\Delta H", category: "Quantities", aliases: ["delta H", "heat of reaction"] },
  { name: "standard enthalpy", latex: "\\Delta H^\\circ", category: "Quantities", aliases: ["delta H naught", "standard state"] },
  { name: "entropy change", latex: "\\Delta S", category: "Quantities", aliases: ["delta S"] },
  { name: "Gibbs free energy", latex: "\\Delta G", category: "Quantities", aliases: ["delta G", "spontaneity"] },
  { name: "equilibrium constant", latex: "K_\\mathrm{eq}", category: "Quantities", aliases: ["Keq", "Kc"] },
  { name: "acid dissociation constant", latex: "K_\\mathrm{a}", category: "Quantities", aliases: ["Ka"] },
  { name: "base dissociation constant", latex: "K_\\mathrm{b}", category: "Quantities", aliases: ["Kb"] },
  { name: "water autoionization constant", latex: "K_\\mathrm{w}", category: "Quantities", aliases: ["Kw"] },
  { name: "solubility product", latex: "K_\\mathrm{sp}", category: "Quantities", aliases: ["Ksp"] },
  { name: "pH", latex: "\\mathrm{pH}", category: "Quantities", aliases: ["acidity"] },
  { name: "pOH", latex: "\\mathrm{pOH}", category: "Quantities" },
  { name: "pKa", latex: "\\mathrm{p}K_\\mathrm{a}", category: "Quantities" },
  { name: "concentration of H+", latex: "[\\ce{H+}]", category: "Quantities", aliases: ["molarity brackets", "concentration"] },
  { name: "Avogadro constant", latex: "N_\\mathrm{A}", category: "Quantities", aliases: ["avogadro number"] },
  // ── Units ──
  { name: "mole", latex: "\\pu{mol}", category: "Units", aliases: ["amount"] },
  { name: "molar (mol/L)", latex: "\\pu{mol/L}", category: "Units", aliases: ["molarity", "concentration unit"] },
  { name: "molar mass (g/mol)", latex: "\\pu{g/mol}", category: "Units" },
  { name: "gram", latex: "\\pu{g}", category: "Units" },
  { name: "liter", latex: "\\pu{L}", category: "Units", aliases: ["litre"] },
  { name: "milliliter", latex: "\\pu{mL}", category: "Units", aliases: ["millilitre"] },
  { name: "kilojoule", latex: "\\pu{kJ}", category: "Units", aliases: ["energy"] },
  { name: "kilojoule per mole", latex: "\\pu{kJ/mol}", category: "Units", aliases: ["molar energy"] },
  { name: "atmosphere", latex: "\\pu{atm}", category: "Units", aliases: ["pressure"] },
  { name: "kilopascal", latex: "\\pu{kPa}", category: "Units", aliases: ["pressure"] },
  { name: "millimeter of mercury", latex: "\\pu{mmHg}", category: "Units", aliases: ["torr", "pressure"] },
  { name: "kelvin", latex: "\\pu{K}", category: "Units", aliases: ["temperature"] },
  { name: "degree Celsius", latex: "\\pu{\\degree C}", category: "Units", aliases: ["temperature", "centigrade"] },
];
