/**
 * The Aquarius symbol library — the searchable catalog of LaTeX symbols that
 * backs the customizable toolbars and the symbol palette.
 *
 * Every `latex` MUST render in KaTeX (the picker shows a live preview), so
 * entries are limited to KaTeX-supported commands (core LaTeX + amssymb + the
 * common math packages KaTeX bundles). `name`/`aliases` drive search; the picker
 * sorts by `name` alphabetically by default.
 */

export interface SymbolEntry {
  /** Human-readable name — the primary search key. */
  name: string;
  /** The LaTeX command to insert and to render as a preview. */
  latex: string;
  /** Grouping label, e.g. "Greek", "Relations", "Arrows". */
  category: string;
  /** Extra search terms. */
  aliases?: string[];
}

export const SYMBOLS: SymbolEntry[] = [
  // ── Greek ──
  { name: "alpha", latex: "\\alpha", category: "Greek" },
  { name: "beta", latex: "\\beta", category: "Greek" },
  { name: "gamma", latex: "\\gamma", category: "Greek" },
  { name: "delta", latex: "\\delta", category: "Greek" },
  { name: "epsilon", latex: "\\epsilon", category: "Greek" },
  { name: "varepsilon", latex: "\\varepsilon", category: "Greek", aliases: ["epsilon variant"] },
  { name: "zeta", latex: "\\zeta", category: "Greek" },
  { name: "eta", latex: "\\eta", category: "Greek" },
  { name: "theta", latex: "\\theta", category: "Greek" },
  { name: "vartheta", latex: "\\vartheta", category: "Greek", aliases: ["theta variant"] },
  { name: "iota", latex: "\\iota", category: "Greek" },
  { name: "kappa", latex: "\\kappa", category: "Greek" },
  { name: "varkappa", latex: "\\varkappa", category: "Greek", aliases: ["kappa variant"] },
  { name: "lambda", latex: "\\lambda", category: "Greek" },
  { name: "mu", latex: "\\mu", category: "Greek" },
  { name: "nu", latex: "\\nu", category: "Greek" },
  { name: "xi", latex: "\\xi", category: "Greek" },
  { name: "omicron", latex: "\\omicron", category: "Greek" },
  { name: "pi", latex: "\\pi", category: "Greek" },
  { name: "varpi", latex: "\\varpi", category: "Greek", aliases: ["pi variant"] },
  { name: "rho", latex: "\\rho", category: "Greek" },
  { name: "varrho", latex: "\\varrho", category: "Greek", aliases: ["rho variant"] },
  { name: "sigma", latex: "\\sigma", category: "Greek" },
  { name: "varsigma", latex: "\\varsigma", category: "Greek", aliases: ["sigma variant"] },
  { name: "tau", latex: "\\tau", category: "Greek" },
  { name: "upsilon", latex: "\\upsilon", category: "Greek" },
  { name: "phi", latex: "\\phi", category: "Greek" },
  { name: "varphi", latex: "\\varphi", category: "Greek", aliases: ["phi variant"] },
  { name: "chi", latex: "\\chi", category: "Greek" },
  { name: "psi", latex: "\\psi", category: "Greek" },
  { name: "omega", latex: "\\omega", category: "Greek" },
  { name: "digamma", latex: "\\digamma", category: "Greek" },
  { name: "Gamma", latex: "\\Gamma", category: "Greek" },
  { name: "Delta", latex: "\\Delta", category: "Greek" },
  { name: "Theta", latex: "\\Theta", category: "Greek" },
  { name: "Lambda", latex: "\\Lambda", category: "Greek" },
  { name: "Xi", latex: "\\Xi", category: "Greek" },
  { name: "Pi", latex: "\\Pi", category: "Greek" },
  { name: "Sigma", latex: "\\Sigma", category: "Greek" },
  { name: "Upsilon", latex: "\\Upsilon", category: "Greek" },
  { name: "Phi", latex: "\\Phi", category: "Greek" },
  { name: "Psi", latex: "\\Psi", category: "Greek" },
  { name: "Omega", latex: "\\Omega", category: "Greek" },
  { name: "var Gamma", latex: "\\varGamma", category: "Greek", aliases: ["italic Gamma"] },
  { name: "var Delta", latex: "\\varDelta", category: "Greek", aliases: ["italic Delta"] },
  { name: "var Theta", latex: "\\varTheta", category: "Greek", aliases: ["italic Theta"] },
  { name: "var Lambda", latex: "\\varLambda", category: "Greek", aliases: ["italic Lambda"] },
  { name: "var Xi", latex: "\\varXi", category: "Greek", aliases: ["italic Xi"] },
  { name: "var Pi", latex: "\\varPi", category: "Greek", aliases: ["italic Pi"] },
  { name: "var Sigma", latex: "\\varSigma", category: "Greek", aliases: ["italic Sigma"] },
  { name: "var Upsilon", latex: "\\varUpsilon", category: "Greek", aliases: ["italic Upsilon"] },
  { name: "var Phi", latex: "\\varPhi", category: "Greek", aliases: ["italic Phi"] },
  { name: "var Psi", latex: "\\varPsi", category: "Greek", aliases: ["italic Psi"] },
  { name: "var Omega", latex: "\\varOmega", category: "Greek", aliases: ["italic Omega"] },
  // ── Operators ──
  { name: "times", latex: "\\times", category: "Operators", aliases: ["multiply", "x"] },
  { name: "divide", latex: "\\div", category: "Operators", aliases: ["division"] },
  { name: "plus minus", latex: "\\pm", category: "Operators", aliases: ["plusminus"] },
  { name: "minus plus", latex: "\\mp", category: "Operators", aliases: ["minusplus"] },
  { name: "cdot", latex: "\\cdot", category: "Operators", aliases: ["dot product", "centered dot"] },
  { name: "asterisk", latex: "\\ast", category: "Operators", aliases: ["star op"] },
  { name: "star", latex: "\\star", category: "Operators" },
  { name: "ring", latex: "\\circ", category: "Operators", aliases: ["composition", "circ"] },
  { name: "bullet", latex: "\\bullet", category: "Operators" },
  { name: "circle plus", latex: "\\oplus", category: "Operators", aliases: ["xor", "direct sum"] },
  { name: "circle minus", latex: "\\ominus", category: "Operators" },
  { name: "circle times", latex: "\\otimes", category: "Operators", aliases: ["tensor", "kronecker"] },
  { name: "circle slash", latex: "\\oslash", category: "Operators" },
  { name: "circle dot", latex: "\\odot", category: "Operators" },
  { name: "intersection", latex: "\\cap", category: "Operators", aliases: ["meet", "and set"] },
  { name: "union", latex: "\\cup", category: "Operators", aliases: ["join", "or set"] },
  { name: "multiset union", latex: "\\uplus", category: "Operators", aliases: ["uplus"] },
  { name: "square cap", latex: "\\sqcap", category: "Operators" },
  { name: "square cup", latex: "\\sqcup", category: "Operators" },
  { name: "logical or", latex: "\\vee", category: "Operators", aliases: ["lor", "disjunction"] },
  { name: "logical and", latex: "\\wedge", category: "Operators", aliases: ["land", "conjunction"] },
  { name: "set minus", latex: "\\setminus", category: "Operators", aliases: ["difference"] },
  { name: "wreath product", latex: "\\wr", category: "Operators" },
  { name: "diamond", latex: "\\diamond", category: "Operators" },
  { name: "big triangle up", latex: "\\bigtriangleup", category: "Operators" },
  { name: "big triangle down", latex: "\\bigtriangledown", category: "Operators" },
  { name: "triangle left", latex: "\\triangleleft", category: "Operators" },
  { name: "triangle right", latex: "\\triangleright", category: "Operators" },
  { name: "amalgamation", latex: "\\amalg", category: "Operators", aliases: ["amalg"] },
  { name: "dagger", latex: "\\dagger", category: "Operators", aliases: ["cross"] },
  { name: "double dagger", latex: "\\ddagger", category: "Operators" },
  { name: "lhd", latex: "\\lhd", category: "Operators", aliases: ["normal subgroup"] },
  { name: "rhd", latex: "\\rhd", category: "Operators" },
  { name: "unlhd", latex: "\\unlhd", category: "Operators" },
  { name: "unrhd", latex: "\\unrhd", category: "Operators" },
  { name: "box plus", latex: "\\boxplus", category: "Operators" },
  { name: "box times", latex: "\\boxtimes", category: "Operators" },
  { name: "box minus", latex: "\\boxminus", category: "Operators" },
  { name: "box dot", latex: "\\boxdot", category: "Operators" },
  { name: "left times", latex: "\\ltimes", category: "Operators", aliases: ["semidirect"] },
  { name: "right times", latex: "\\rtimes", category: "Operators", aliases: ["semidirect"] },
  { name: "divide on times", latex: "\\divideontimes", category: "Operators" },
  { name: "center dot", latex: "\\centerdot", category: "Operators" },
  { name: "intercalate", latex: "\\intercal", category: "Operators", aliases: ["transpose"] },
  { name: "dotplus", latex: "\\dotplus", category: "Operators" },
  { name: "curl or", latex: "\\curlyvee", category: "Operators" },
  { name: "curl and", latex: "\\curlywedge", category: "Operators" },
  { name: "double cap", latex: "\\doublecap", category: "Operators", aliases: ["Cap"] },
  { name: "double cup", latex: "\\doublecup", category: "Operators", aliases: ["Cup"] },
  { name: "smallsetminus", latex: "\\smallsetminus", category: "Operators" },
  { name: "barwedge", latex: "\\barwedge", category: "Operators" },
  { name: "veebar", latex: "\\veebar", category: "Operators", aliases: ["xor"] },
  { name: "circled ast", latex: "\\circledast", category: "Operators" },
  { name: "circled circ", latex: "\\circledcirc", category: "Operators" },
  { name: "circled dash", latex: "\\circleddash", category: "Operators" },
  { name: "gtr dot", latex: "\\gtrdot", category: "Operators" },
  { name: "less dot", latex: "\\lessdot", category: "Operators" },
  // ── Relations ──
  { name: "equals", latex: "=", category: "Relations", aliases: ["eq"] },
  { name: "not equal", latex: "\\neq", category: "Relations", aliases: ["ne", "ne not equal"] },
  { name: "less than", latex: "<", category: "Relations", aliases: ["lt"] },
  { name: "greater than", latex: ">", category: "Relations", aliases: ["gt"] },
  { name: "less than or equal", latex: "\\leq", category: "Relations", aliases: ["le", "leq"] },
  { name: "greater than or equal", latex: "\\geq", category: "Relations", aliases: ["ge", "geq"] },
  { name: "less than or slanted equal", latex: "\\leqslant", category: "Relations", aliases: ["leqslant"] },
  { name: "greater than or slanted equal", latex: "\\geqslant", category: "Relations", aliases: ["geqslant"] },
  { name: "much less than", latex: "\\ll", category: "Relations" },
  { name: "much greater than", latex: "\\gg", category: "Relations" },
  { name: "very much less than", latex: "\\lll", category: "Relations" },
  { name: "very much greater than", latex: "\\ggg", category: "Relations" },
  { name: "precedes", latex: "\\prec", category: "Relations" },
  { name: "succeeds", latex: "\\succ", category: "Relations" },
  { name: "precedes or equal", latex: "\\preceq", category: "Relations" },
  { name: "succeeds or equal", latex: "\\succeq", category: "Relations" },
  { name: "similar", latex: "\\sim", category: "Relations", aliases: ["tilde rel"] },
  { name: "similar equal", latex: "\\simeq", category: "Relations", aliases: ["asymptotically equal"] },
  { name: "approximately", latex: "\\approx", category: "Relations", aliases: ["approx"] },
  { name: "approximately equal", latex: "\\approxeq", category: "Relations" },
  { name: "congruent", latex: "\\cong", category: "Relations", aliases: ["isomorphic"] },
  { name: "equivalent", latex: "\\equiv", category: "Relations", aliases: ["identical"] },
  { name: "asymptotic", latex: "\\asymp", category: "Relations" },
  { name: "dot equals", latex: "\\doteq", category: "Relations", aliases: ["defined as"] },
  { name: "proportional to", latex: "\\propto", category: "Relations", aliases: ["proportional"] },
  { name: "models", latex: "\\models", category: "Relations", aliases: ["entails"] },
  { name: "proves", latex: "\\vdash", category: "Relations", aliases: ["turnstile", "vdash"] },
  { name: "dashv", latex: "\\dashv", category: "Relations" },
  { name: "perpendicular", latex: "\\perp", category: "Relations", aliases: ["orthogonal"] },
  { name: "mid", latex: "\\mid", category: "Relations", aliases: ["divides", "such that"] },
  { name: "parallel", latex: "\\parallel", category: "Relations" },
  { name: "not divides", latex: "\\nmid", category: "Relations", aliases: ["nmid"] },
  { name: "not parallel", latex: "\\nparallel", category: "Relations" },
  { name: "subset", latex: "\\subset", category: "Relations", aliases: ["proper subset"] },
  { name: "superset", latex: "\\supset", category: "Relations" },
  { name: "subset or equal", latex: "\\subseteq", category: "Relations" },
  { name: "superset or equal", latex: "\\supseteq", category: "Relations" },
  { name: "subset not equal", latex: "\\subsetneq", category: "Relations" },
  { name: "superset not equal", latex: "\\supsetneq", category: "Relations" },
  { name: "square subset", latex: "\\sqsubset", category: "Relations" },
  { name: "square superset", latex: "\\sqsupset", category: "Relations" },
  { name: "square subset or equal", latex: "\\sqsubseteq", category: "Relations" },
  { name: "square superset or equal", latex: "\\sqsupseteq", category: "Relations" },
  { name: "element of", latex: "\\in", category: "Relations", aliases: ["member", "belongs to"] },
  { name: "contains", latex: "\\ni", category: "Relations", aliases: ["owns", "ni"] },
  { name: "not element of", latex: "\\notin", category: "Relations", aliases: ["not member", "notin"] },
  { name: "bowtie", latex: "\\bowtie", category: "Relations" },
  { name: "join", latex: "\\Join", category: "Relations" },
  { name: "smile", latex: "\\smile", category: "Relations" },
  { name: "frown", latex: "\\frown", category: "Relations" },
  { name: "less or similar", latex: "\\lesssim", category: "Relations" },
  { name: "greater or similar", latex: "\\gtrsim", category: "Relations" },
  { name: "less greater", latex: "\\lessgtr", category: "Relations" },
  { name: "greater less", latex: "\\gtrless", category: "Relations" },
  { name: "equal slant less", latex: "\\eqslantless", category: "Relations" },
  { name: "equal slant greater", latex: "\\eqslantgtr", category: "Relations" },
  { name: "between", latex: "\\between", category: "Relations" },
  { name: "pitchfork", latex: "\\pitchfork", category: "Relations" },
  { name: "double turnstile", latex: "\\vDash", category: "Relations", aliases: ["vDash", "satisfies"] },
  { name: "forces", latex: "\\Vdash", category: "Relations", aliases: ["Vdash"] },
  { name: "triple turnstile", latex: "\\Vvdash", category: "Relations" },
  { name: "not greater than or equal", latex: "\\ngeq", category: "Relations", aliases: ["ngeq"] },
  { name: "not less than or equal", latex: "\\nleq", category: "Relations", aliases: ["nleq"] },
  { name: "not less than", latex: "\\nless", category: "Relations" },
  { name: "not greater than", latex: "\\ngtr", category: "Relations" },
  { name: "not similar", latex: "\\nsim", category: "Relations" },
  { name: "not congruent", latex: "\\ncong", category: "Relations" },
  { name: "not subset or equal", latex: "\\nsubseteq", category: "Relations" },
  { name: "not superset or equal", latex: "\\nsupseteq", category: "Relations" },
  { name: "precedes similar", latex: "\\precsim", category: "Relations" },
  { name: "succeeds similar", latex: "\\succsim", category: "Relations" },
  { name: "not precedes", latex: "\\nprec", category: "Relations" },
  { name: "not succeeds", latex: "\\nsucc", category: "Relations" },
  { name: "subset double", latex: "\\Subset", category: "Relations" },
  { name: "superset double", latex: "\\Supset", category: "Relations" },
  { name: "triangle equal", latex: "\\triangleq", category: "Relations", aliases: ["definition"] },
  { name: "doteqdot", latex: "\\doteqdot", category: "Relations" },
  { name: "fall down equal", latex: "\\fallingdotseq", category: "Relations" },
  { name: "rise up equal", latex: "\\risingdotseq", category: "Relations" },
  { name: "backsimilar", latex: "\\backsim", category: "Relations" },
  { name: "circle equal", latex: "\\circeq", category: "Relations" },
  // ── Arrows ──
  { name: "leftarrow", latex: "\\leftarrow", category: "Arrows", aliases: ["gets", "left arrow"] },
  { name: "rightarrow", latex: "\\rightarrow", category: "Arrows", aliases: ["to", "right arrow"] },
  { name: "leftrightarrow", latex: "\\leftrightarrow", category: "Arrows" },
  { name: "Leftarrow", latex: "\\Leftarrow", category: "Arrows", aliases: ["implied by"] },
  { name: "Rightarrow", latex: "\\Rightarrow", category: "Arrows", aliases: ["implies"] },
  { name: "Leftrightarrow", latex: "\\Leftrightarrow", category: "Arrows", aliases: ["iff", "if and only if"] },
  { name: "long leftarrow", latex: "\\longleftarrow", category: "Arrows" },
  { name: "long rightarrow", latex: "\\longrightarrow", category: "Arrows" },
  { name: "long leftrightarrow", latex: "\\longleftrightarrow", category: "Arrows" },
  { name: "long Leftarrow", latex: "\\Longleftarrow", category: "Arrows" },
  { name: "long Rightarrow", latex: "\\Longrightarrow", category: "Arrows" },
  { name: "long Leftrightarrow", latex: "\\Longleftrightarrow", category: "Arrows" },
  { name: "maps to", latex: "\\mapsto", category: "Arrows" },
  { name: "long maps to", latex: "\\longmapsto", category: "Arrows" },
  { name: "hook left arrow", latex: "\\hookleftarrow", category: "Arrows" },
  { name: "hook right arrow", latex: "\\hookrightarrow", category: "Arrows", aliases: ["injection"] },
  { name: "left harpoon up", latex: "\\leftharpoonup", category: "Arrows" },
  { name: "right harpoon up", latex: "\\rightharpoonup", category: "Arrows" },
  { name: "left harpoon down", latex: "\\leftharpoondown", category: "Arrows" },
  { name: "right harpoon down", latex: "\\rightharpoondown", category: "Arrows" },
  { name: "right left harpoons", latex: "\\rightleftharpoons", category: "Arrows", aliases: ["equilibrium"] },
  { name: "left right harpoons", latex: "\\leftrightharpoons", category: "Arrows" },
  { name: "up arrow", latex: "\\uparrow", category: "Arrows" },
  { name: "down arrow", latex: "\\downarrow", category: "Arrows" },
  { name: "up down arrow", latex: "\\updownarrow", category: "Arrows" },
  { name: "Up arrow", latex: "\\Uparrow", category: "Arrows" },
  { name: "Down arrow", latex: "\\Downarrow", category: "Arrows" },
  { name: "Up down arrow", latex: "\\Updownarrow", category: "Arrows" },
  { name: "northeast arrow", latex: "\\nearrow", category: "Arrows" },
  { name: "southeast arrow", latex: "\\searrow", category: "Arrows" },
  { name: "southwest arrow", latex: "\\swarrow", category: "Arrows" },
  { name: "northwest arrow", latex: "\\nwarrow", category: "Arrows" },
  { name: "leads to", latex: "\\leadsto", category: "Arrows" },
  { name: "to", latex: "\\to", category: "Arrows", aliases: ["maps", "rightarrow short"] },
  { name: "gets", latex: "\\gets", category: "Arrows", aliases: ["leftarrow short"] },
  { name: "implies", latex: "\\implies", category: "Arrows", aliases: ["therefore arrow"] },
  { name: "implied by", latex: "\\impliedby", category: "Arrows" },
  { name: "iff", latex: "\\iff", category: "Arrows", aliases: ["if and only if"] },
  { name: "not leftarrow", latex: "\\nleftarrow", category: "Arrows" },
  { name: "not rightarrow", latex: "\\nrightarrow", category: "Arrows" },
  { name: "not Leftarrow", latex: "\\nLeftarrow", category: "Arrows" },
  { name: "not Rightarrow", latex: "\\nRightarrow", category: "Arrows" },
  { name: "not Leftrightarrow", latex: "\\nLeftrightarrow", category: "Arrows" },
  { name: "two head right arrow", latex: "\\twoheadrightarrow", category: "Arrows", aliases: ["surjection"] },
  { name: "two head left arrow", latex: "\\twoheadleftarrow", category: "Arrows" },
  { name: "right arrow tail", latex: "\\rightarrowtail", category: "Arrows", aliases: ["injection"] },
  { name: "left arrow tail", latex: "\\leftarrowtail", category: "Arrows" },
  { name: "curve arrow right", latex: "\\curvearrowright", category: "Arrows" },
  { name: "curve arrow left", latex: "\\curvearrowleft", category: "Arrows" },
  { name: "circle arrow right", latex: "\\circlearrowright", category: "Arrows" },
  { name: "circle arrow left", latex: "\\circlearrowleft", category: "Arrows" },
  { name: "loop arrow right", latex: "\\looparrowright", category: "Arrows" },
  { name: "loop arrow left", latex: "\\looparrowleft", category: "Arrows" },
  { name: "right squiggle arrow", latex: "\\rightsquigarrow", category: "Arrows" },
  { name: "left right squiggle arrow", latex: "\\leftrightsquigarrow", category: "Arrows" },
  { name: "downharpoon right", latex: "\\downharpoonright", category: "Arrows" },
  { name: "downharpoon left", latex: "\\downharpoonleft", category: "Arrows" },
  { name: "upharpoon right", latex: "\\upharpoonright", category: "Arrows" },
  { name: "upharpoon left", latex: "\\upharpoonleft", category: "Arrows" },
  { name: "dashed right arrow", latex: "\\dashrightarrow", category: "Arrows" },
  { name: "dashed left arrow", latex: "\\dashleftarrow", category: "Arrows" },
  { name: "left left arrows", latex: "\\leftleftarrows", category: "Arrows" },
  { name: "right right arrows", latex: "\\rightrightarrows", category: "Arrows" },
  { name: "left right arrows", latex: "\\leftrightarrows", category: "Arrows" },
  { name: "right left arrows", latex: "\\rightleftarrows", category: "Arrows" },
  { name: "upup arrows", latex: "\\upuparrows", category: "Arrows" },
  { name: "downdown arrows", latex: "\\downdownarrows", category: "Arrows" },
  { name: "xrightarrow template", latex: "\\xrightarrow{}", category: "Arrows", aliases: ["labeled arrow"] },
  { name: "xleftarrow template", latex: "\\xleftarrow{}", category: "Arrows", aliases: ["labeled arrow"] },
  // ── Big operators ──
  { name: "sum", latex: "\\sum", category: "Big operators", aliases: ["sigma sum"] },
  { name: "sum (template)", latex: "\\sum_{}^{}", category: "Big operators", aliases: ["summation"] },
  { name: "product", latex: "\\prod", category: "Big operators" },
  { name: "product (template)", latex: "\\prod_{}^{}", category: "Big operators" },
  { name: "coproduct", latex: "\\coprod", category: "Big operators" },
  { name: "coproduct (template)", latex: "\\coprod_{}^{}", category: "Big operators" },
  { name: "integral", latex: "\\int", category: "Big operators" },
  { name: "integral (template)", latex: "\\int_{}^{}", category: "Big operators", aliases: ["definite integral"] },
  { name: "double integral", latex: "\\iint", category: "Big operators" },
  { name: "triple integral", latex: "\\iiint", category: "Big operators" },
  { name: "contour integral", latex: "\\oint", category: "Big operators", aliases: ["line integral"] },
  { name: "big union", latex: "\\bigcup", category: "Big operators" },
  { name: "big union (template)", latex: "\\bigcup_{}^{}", category: "Big operators" },
  { name: "big intersection", latex: "\\bigcap", category: "Big operators" },
  { name: "big intersection (template)", latex: "\\bigcap_{}^{}", category: "Big operators" },
  { name: "big square union", latex: "\\bigsqcup", category: "Big operators" },
  { name: "big or", latex: "\\bigvee", category: "Big operators" },
  { name: "big and", latex: "\\bigwedge", category: "Big operators" },
  { name: "big circle plus", latex: "\\bigoplus", category: "Big operators", aliases: ["direct sum big"] },
  { name: "big circle times", latex: "\\bigotimes", category: "Big operators" },
  { name: "big circle dot", latex: "\\bigodot", category: "Big operators" },
  { name: "big multiset union", latex: "\\biguplus", category: "Big operators" },
  // ── Delimiters ──
  { name: "left angle", latex: "\\langle", category: "Delimiters", aliases: ["bra"] },
  { name: "right angle", latex: "\\rangle", category: "Delimiters", aliases: ["ket"] },
  { name: "left ceiling", latex: "\\lceil", category: "Delimiters" },
  { name: "right ceiling", latex: "\\rceil", category: "Delimiters" },
  { name: "left floor", latex: "\\lfloor", category: "Delimiters" },
  { name: "right floor", latex: "\\rfloor", category: "Delimiters" },
  { name: "left vertical bar", latex: "\\lvert", category: "Delimiters", aliases: ["abs left"] },
  { name: "right vertical bar", latex: "\\rvert", category: "Delimiters", aliases: ["abs right"] },
  { name: "left double bar", latex: "\\lVert", category: "Delimiters", aliases: ["norm left"] },
  { name: "right double bar", latex: "\\rVert", category: "Delimiters", aliases: ["norm right"] },
  { name: "vertical bar", latex: "|", category: "Delimiters", aliases: ["pipe", "absolute value"] },
  { name: "double vertical bar", latex: "\\|", category: "Delimiters", aliases: ["norm"] },
  { name: "backslash", latex: "\\backslash", category: "Delimiters" },
  { name: "left parenthesis", latex: "(", category: "Delimiters" },
  { name: "right parenthesis", latex: ")", category: "Delimiters" },
  { name: "left bracket", latex: "[", category: "Delimiters", aliases: ["square bracket"] },
  { name: "right bracket", latex: "]", category: "Delimiters" },
  { name: "left brace", latex: "\\{", category: "Delimiters", aliases: ["curly brace"] },
  { name: "right brace", latex: "\\}", category: "Delimiters" },
  { name: "left brace big", latex: "\\lbrace", category: "Delimiters" },
  { name: "right brace big", latex: "\\rbrace", category: "Delimiters" },
  { name: "left bracket cmd", latex: "\\lbrack", category: "Delimiters" },
  { name: "right bracket cmd", latex: "\\rbrack", category: "Delimiters" },
  { name: "group begin", latex: "\\lgroup", category: "Delimiters" },
  { name: "group end", latex: "\\rgroup", category: "Delimiters" },
  { name: "absolute value (template)", latex: "\\left|\\right|", category: "Delimiters", aliases: ["abs"] },
  { name: "norm (template)", latex: "\\left\\|\\right\\|", category: "Delimiters", aliases: ["norm bars"] },
  { name: "auto parentheses (template)", latex: "\\left(\\right)", category: "Delimiters", aliases: ["big parens"] },
  { name: "auto brackets (template)", latex: "\\left[\\right]", category: "Delimiters" },
  { name: "auto braces (template)", latex: "\\left\\{\\right\\}", category: "Delimiters" },
  { name: "auto angle (template)", latex: "\\left\\langle\\right\\rangle", category: "Delimiters", aliases: ["inner product"] },
  // ── Sets & logic ──
  { name: "for all", latex: "\\forall", category: "Sets & logic", aliases: ["universal"] },
  { name: "there exists", latex: "\\exists", category: "Sets & logic", aliases: ["existential"] },
  { name: "there does not exist", latex: "\\nexists", category: "Sets & logic", aliases: ["nexists"] },
  { name: "negation", latex: "\\neg", category: "Sets & logic", aliases: ["not"] },
  { name: "logical not", latex: "\\lnot", category: "Sets & logic", aliases: ["not"] },
  { name: "and", latex: "\\land", category: "Sets & logic", aliases: ["conjunction", "logical and"] },
  { name: "or", latex: "\\lor", category: "Sets & logic", aliases: ["disjunction", "logical or"] },
  { name: "empty set", latex: "\\emptyset", category: "Sets & logic", aliases: ["null set"] },
  { name: "empty set variant", latex: "\\varnothing", category: "Sets & logic", aliases: ["null set"] },
  { name: "infinity", latex: "\\infty", category: "Sets & logic", aliases: ["infinite"] },
  { name: "aleph", latex: "\\aleph", category: "Sets & logic", aliases: ["cardinality"] },
  { name: "beth", latex: "\\beth", category: "Sets & logic" },
  { name: "gimel", latex: "\\gimel", category: "Sets & logic" },
  { name: "daleth", latex: "\\daleth", category: "Sets & logic" },
  { name: "complement", latex: "\\complement", category: "Sets & logic", aliases: ["set complement"] },
  { name: "weierstrass p", latex: "\\wp", category: "Sets & logic", aliases: ["power set"] },
  { name: "real part", latex: "\\Re", category: "Sets & logic", aliases: ["real"] },
  { name: "imaginary part", latex: "\\Im", category: "Sets & logic", aliases: ["imaginary"] },
  { name: "h bar", latex: "\\hbar", category: "Sets & logic", aliases: ["planck"] },
  { name: "script l", latex: "\\ell", category: "Sets & logic", aliases: ["ell"] },
  { name: "partial", latex: "\\partial", category: "Sets & logic", aliases: ["partial derivative"] },
  { name: "nabla", latex: "\\nabla", category: "Sets & logic", aliases: ["del", "gradient"] },
  { name: "top", latex: "\\top", category: "Sets & logic", aliases: ["true", "tautology"] },
  { name: "bottom", latex: "\\bot", category: "Sets & logic", aliases: ["false", "contradiction"] },
  { name: "angle", latex: "\\angle", category: "Sets & logic" },
  { name: "measured angle", latex: "\\measuredangle", category: "Sets & logic" },
  { name: "spherical angle", latex: "\\sphericalangle", category: "Sets & logic" },
  { name: "triangle", latex: "\\triangle", category: "Sets & logic" },
  { name: "square", latex: "\\square", category: "Sets & logic", aliases: ["box", "qed open"] },
  { name: "black square", latex: "\\blacksquare", category: "Sets & logic", aliases: ["qed"] },
  { name: "lozenge", latex: "\\lozenge", category: "Sets & logic", aliases: ["diamond shape"] },
  { name: "black lozenge", latex: "\\blacklozenge", category: "Sets & logic" },
  { name: "surd", latex: "\\surd", category: "Sets & logic", aliases: ["root sign"] },
  { name: "flat", latex: "\\flat", category: "Sets & logic", aliases: ["music flat"] },
  { name: "natural", latex: "\\natural", category: "Sets & logic", aliases: ["music natural"] },
  { name: "sharp", latex: "\\sharp", category: "Sets & logic", aliases: ["music sharp"] },
  { name: "club suit", latex: "\\clubsuit", category: "Sets & logic", aliases: ["clubs"] },
  { name: "diamond suit", latex: "\\diamondsuit", category: "Sets & logic", aliases: ["diamonds"] },
  { name: "heart suit", latex: "\\heartsuit", category: "Sets & logic", aliases: ["hearts"] },
  { name: "spade suit", latex: "\\spadesuit", category: "Sets & logic", aliases: ["spades"] },
  { name: "therefore", latex: "\\therefore", category: "Sets & logic" },
  { name: "because", latex: "\\because", category: "Sets & logic" },
  { name: "mho", latex: "\\mho", category: "Sets & logic", aliases: ["inverted ohm"] },
  { name: "prime", latex: "\\prime", category: "Sets & logic", aliases: ["derivative mark"] },
  { name: "back prime", latex: "\\backprime", category: "Sets & logic" },
  { name: "checkmark", latex: "\\checkmark", category: "Sets & logic", aliases: ["check", "tick"] },
  { name: "maltese", latex: "\\maltese", category: "Sets & logic", aliases: ["maltese cross"] },
  { name: "black triangle", latex: "\\blacktriangle", category: "Sets & logic" },
  { name: "black triangle down", latex: "\\blacktriangledown", category: "Sets & logic" },
  { name: "circled S", latex: "\\circledS", category: "Sets & logic" },
  { name: "circled R", latex: "\\circledR", category: "Sets & logic", aliases: ["registered"] },
  { name: "finite cardinality", latex: "\\Finv", category: "Sets & logic" },
  { name: "game", latex: "\\Game", category: "Sets & logic" },
  { name: "eth", latex: "\\eth", category: "Sets & logic" },
  { name: "bigstar", latex: "\\bigstar", category: "Sets & logic", aliases: ["filled star"] },
  { name: "diagonal up", latex: "\\diagup", category: "Sets & logic" },
  { name: "diagonal down", latex: "\\diagdown", category: "Sets & logic" },
  // ── Functions ──
  { name: "sine", latex: "\\sin", category: "Functions", aliases: ["sin"] },
  { name: "cosine", latex: "\\cos", category: "Functions", aliases: ["cos"] },
  { name: "tangent", latex: "\\tan", category: "Functions", aliases: ["tan"] },
  { name: "cotangent", latex: "\\cot", category: "Functions", aliases: ["cot"] },
  { name: "secant", latex: "\\sec", category: "Functions", aliases: ["sec"] },
  { name: "cosecant", latex: "\\csc", category: "Functions", aliases: ["csc"] },
  { name: "arcsine", latex: "\\arcsin", category: "Functions", aliases: ["arcsin", "inverse sine"] },
  { name: "arccosine", latex: "\\arccos", category: "Functions", aliases: ["arccos"] },
  { name: "arctangent", latex: "\\arctan", category: "Functions", aliases: ["arctan"] },
  { name: "hyperbolic sine", latex: "\\sinh", category: "Functions", aliases: ["sinh"] },
  { name: "hyperbolic cosine", latex: "\\cosh", category: "Functions", aliases: ["cosh"] },
  { name: "hyperbolic tangent", latex: "\\tanh", category: "Functions", aliases: ["tanh"] },
  { name: "hyperbolic cotangent", latex: "\\coth", category: "Functions", aliases: ["coth"] },
  { name: "logarithm", latex: "\\log", category: "Functions", aliases: ["log"] },
  { name: "natural log", latex: "\\ln", category: "Functions", aliases: ["ln"] },
  { name: "log base 10", latex: "\\lg", category: "Functions", aliases: ["lg"] },
  { name: "exponential", latex: "\\exp", category: "Functions", aliases: ["exp"] },
  { name: "limit", latex: "\\lim", category: "Functions" },
  { name: "limit (template)", latex: "\\lim_{}", category: "Functions", aliases: ["limit to"] },
  { name: "limit superior", latex: "\\limsup", category: "Functions", aliases: ["limsup"] },
  { name: "limit inferior", latex: "\\liminf", category: "Functions", aliases: ["liminf"] },
  { name: "maximum", latex: "\\max", category: "Functions", aliases: ["max"] },
  { name: "minimum", latex: "\\min", category: "Functions", aliases: ["min"] },
  { name: "supremum", latex: "\\sup", category: "Functions", aliases: ["sup"] },
  { name: "infimum", latex: "\\inf", category: "Functions", aliases: ["inf"] },
  { name: "determinant", latex: "\\det", category: "Functions", aliases: ["det"] },
  { name: "dimension", latex: "\\dim", category: "Functions", aliases: ["dim"] },
  { name: "kernel", latex: "\\ker", category: "Functions", aliases: ["ker"] },
  { name: "degree (function)", latex: "\\deg", category: "Functions", aliases: ["deg"] },
  { name: "greatest common divisor", latex: "\\gcd", category: "Functions", aliases: ["gcd"] },
  { name: "homomorphism", latex: "\\hom", category: "Functions", aliases: ["hom"] },
  { name: "argument", latex: "\\arg", category: "Functions", aliases: ["arg"] },
  { name: "probability", latex: "\\Pr", category: "Functions", aliases: ["Pr"] },
  { name: "binary mod", latex: "\\bmod", category: "Functions", aliases: ["modulo", "mod"] },
  { name: "paren mod (template)", latex: "\\pmod{}", category: "Functions", aliases: ["modulo"] },
  { name: "injective limit", latex: "\\varinjlim", category: "Functions" },
  { name: "projective limit", latex: "\\varprojlim", category: "Functions" },
  // ── Accents ──
  { name: "hat", latex: "\\hat{}", category: "Accents", aliases: ["circumflex"] },
  { name: "wide hat", latex: "\\widehat{}", category: "Accents" },
  { name: "bar", latex: "\\bar{}", category: "Accents", aliases: ["macron"] },
  { name: "overline", latex: "\\overline{}", category: "Accents" },
  { name: "underline", latex: "\\underline{}", category: "Accents" },
  { name: "vector", latex: "\\vec{}", category: "Accents", aliases: ["arrow accent"] },
  { name: "over right arrow", latex: "\\overrightarrow{}", category: "Accents" },
  { name: "over left arrow", latex: "\\overleftarrow{}", category: "Accents" },
  { name: "over left right arrow", latex: "\\overleftrightarrow{}", category: "Accents" },
  { name: "dot accent", latex: "\\dot{}", category: "Accents", aliases: ["derivative dot"] },
  { name: "double dot accent", latex: "\\ddot{}", category: "Accents", aliases: ["second derivative"] },
  { name: "triple dot accent", latex: "\\dddot{}", category: "Accents" },
  { name: "tilde accent", latex: "\\tilde{}", category: "Accents" },
  { name: "wide tilde", latex: "\\widetilde{}", category: "Accents" },
  { name: "check accent", latex: "\\check{}", category: "Accents", aliases: ["caron"] },
  { name: "breve accent", latex: "\\breve{}", category: "Accents" },
  { name: "acute accent", latex: "\\acute{}", category: "Accents" },
  { name: "grave accent", latex: "\\grave{}", category: "Accents" },
  { name: "mathring accent", latex: "\\mathring{}", category: "Accents", aliases: ["ring above"] },
  { name: "over brace", latex: "\\overbrace{}", category: "Accents" },
  { name: "under brace", latex: "\\underbrace{}", category: "Accents" },
  { name: "over set (template)", latex: "\\overset{}{}", category: "Accents" },
  { name: "under set (template)", latex: "\\underset{}{}", category: "Accents" },
  { name: "under brace label (template)", latex: "\\underbrace{}_{}", category: "Accents" },
  { name: "over brace label (template)", latex: "\\overbrace{}^{}", category: "Accents" },
  // ── Structures ──
  { name: "fraction", latex: "\\frac{}{}", category: "Structures", aliases: ["over"] },
  { name: "display fraction", latex: "\\dfrac{}{}", category: "Structures", aliases: ["big fraction"] },
  { name: "text fraction", latex: "\\tfrac{}{}", category: "Structures", aliases: ["inline fraction"] },
  { name: "continued fraction", latex: "\\cfrac{}{}", category: "Structures" },
  { name: "square root", latex: "\\sqrt{}", category: "Structures", aliases: ["radical"] },
  { name: "nth root", latex: "\\sqrt[]{}", category: "Structures", aliases: ["radical index"] },
  { name: "binomial", latex: "\\binom{}{}", category: "Structures", aliases: ["choose", "n choose k"] },
  { name: "display binomial", latex: "\\dbinom{}{}", category: "Structures" },
  { name: "text binomial", latex: "\\tbinom{}{}", category: "Structures" },
  { name: "superscript", latex: "^{}", category: "Structures", aliases: ["power", "exponent"] },
  { name: "subscript", latex: "_{}", category: "Structures", aliases: ["index"] },
  { name: "sub and superscript", latex: "_{}^{}", category: "Structures", aliases: ["sub super"] },
  { name: "boxed", latex: "\\boxed{}", category: "Structures", aliases: ["box around"] },
  { name: "text", latex: "\\text{x}", category: "Structures", aliases: ["roman text"] },
  { name: "substack (template)", latex: "\\substack{}", category: "Structures", aliases: ["multiline subscript"] },
  { name: "stacked rel (template)", latex: "\\stackrel{}{}", category: "Structures" },
  { name: "matrix (template)", latex: "\\begin{matrix}\\end{matrix}", category: "Structures", aliases: ["array"] },
  { name: "parenthesized matrix (template)", latex: "\\begin{pmatrix}\\end{pmatrix}", category: "Structures", aliases: ["pmatrix"] },
  { name: "bracket matrix (template)", latex: "\\begin{bmatrix}\\end{bmatrix}", category: "Structures", aliases: ["bmatrix"] },
  { name: "braced matrix (template)", latex: "\\begin{Bmatrix}\\end{Bmatrix}", category: "Structures" },
  { name: "determinant matrix (template)", latex: "\\begin{vmatrix}\\end{vmatrix}", category: "Structures", aliases: ["vmatrix", "determinant"] },
  { name: "norm matrix (template)", latex: "\\begin{Vmatrix}\\end{Vmatrix}", category: "Structures" },
  { name: "cases (template)", latex: "\\begin{cases}\\end{cases}", category: "Structures", aliases: ["piecewise"] },
  { name: "aligned (template)", latex: "\\begin{aligned}\\end{aligned}", category: "Structures" },
  { name: "smallmatrix (template)", latex: "\\begin{smallmatrix}\\end{smallmatrix}", category: "Structures", aliases: ["inline matrix"] },
  { name: "bold math", latex: "\\mathbf{}", category: "Structures", aliases: ["boldface"] },
  { name: "blackboard bold", latex: "\\mathbb{}", category: "Structures", aliases: ["double struck"] },
  { name: "calligraphic", latex: "\\mathcal{}", category: "Structures", aliases: ["script caps"] },
  { name: "fraktur", latex: "\\mathfrak{}", category: "Structures", aliases: ["gothic"] },
  { name: "roman math", latex: "\\mathrm{}", category: "Structures", aliases: ["upright"] },
  { name: "italic math", latex: "\\mathit{}", category: "Structures" },
  { name: "script", latex: "\\mathscr{}", category: "Structures", aliases: ["scriptstyle font"] },
  { name: "sans serif math", latex: "\\mathsf{}", category: "Structures", aliases: ["sans"] },
  { name: "typewriter math", latex: "\\mathtt{}", category: "Structures", aliases: ["monospace"] },
  { name: "bold symbol", latex: "\\boldsymbol{}", category: "Structures", aliases: ["bold greek"] },
  { name: "operator name (template)", latex: "\\operatorname{}", category: "Structures", aliases: ["custom function"] },
  // ── Blackboard ──
  { name: "real numbers", latex: "\\mathbb{R}", category: "Blackboard", aliases: ["reals"] },
  { name: "natural numbers", latex: "\\mathbb{N}", category: "Blackboard", aliases: ["naturals"] },
  { name: "integers", latex: "\\mathbb{Z}", category: "Blackboard", aliases: ["whole numbers"] },
  { name: "rational numbers", latex: "\\mathbb{Q}", category: "Blackboard", aliases: ["rationals"] },
  { name: "complex numbers", latex: "\\mathbb{C}", category: "Blackboard", aliases: ["complex"] },
  { name: "quaternions", latex: "\\mathbb{H}", category: "Blackboard", aliases: ["hamilton"] },
  { name: "projective space", latex: "\\mathbb{P}", category: "Blackboard", aliases: ["primes"] },
  { name: "finite field", latex: "\\mathbb{F}", category: "Blackboard", aliases: ["field"] },
  { name: "expectation", latex: "\\mathbb{E}", category: "Blackboard", aliases: ["expected value"] },
  { name: "indicator", latex: "\\mathbb{1}", category: "Blackboard", aliases: ["one"] },
  { name: "special set S", latex: "\\mathbb{S}", category: "Blackboard", aliases: ["sphere"] },
  { name: "special set K", latex: "\\mathbb{K}", category: "Blackboard", aliases: ["field K"] },
  // ── Misc ──
  { name: "low dots", latex: "\\ldots", category: "Misc", aliases: ["ellipsis"] },
  { name: "centered dots", latex: "\\cdots", category: "Misc", aliases: ["middle ellipsis"] },
  { name: "vertical dots", latex: "\\vdots", category: "Misc" },
  { name: "diagonal dots", latex: "\\ddots", category: "Misc" },
  { name: "dots", latex: "\\dots", category: "Misc", aliases: ["ellipsis"] },
  { name: "degree symbol", latex: "^{\\circ}", category: "Misc", aliases: ["degrees"] },
  { name: "dotless i", latex: "\\imath", category: "Misc" },
  { name: "dotless j", latex: "\\jmath", category: "Misc" },
  { name: "prime symbol", latex: "'", category: "Misc", aliases: ["derivative"] },
  { name: "percent", latex: "\\%", category: "Misc", aliases: ["percentage"] },
  { name: "dollar", latex: "\\$", category: "Misc" },
  { name: "ampersand", latex: "\\&", category: "Misc" },
  { name: "hash", latex: "\\#", category: "Misc", aliases: ["number sign"] },
  { name: "underscore char", latex: "\\_", category: "Misc" },
  { name: "braces literal", latex: "\\{\\}", category: "Misc", aliases: ["empty set braces"] },
  { name: "colon", latex: "\\colon", category: "Misc" },
  { name: "center dots low", latex: "\\dotsb", category: "Misc", aliases: ["binary dots"] },
  { name: "thin space", latex: "\\,", category: "Misc", aliases: ["small space"] },
  { name: "medium space", latex: "\\:", category: "Misc" },
  { name: "thick space", latex: "\\;", category: "Misc" },
  { name: "quad space", latex: "\\quad", category: "Misc", aliases: ["space"] },
  { name: "double quad space", latex: "\\qquad", category: "Misc", aliases: ["big space"] },
  { name: "negative thin space", latex: "\\!", category: "Misc" },
  { name: "phantom (template)", latex: "\\phantom{}", category: "Misc", aliases: ["invisible"] },
  { name: "not (template)", latex: "\\not", category: "Misc", aliases: ["slash through"] },
];
